export const portraitMap = {
  '诸葛亮': '/art/portrait-zhugeliang.png',
  '曹操':   '/art/portrait-caocao.png',
  '关羽':   '/art/portrait-guanyu.png',
  '张飞':   '/art/portrait-zhangfei.png',
  '周瑜':   '/art/portrait-zhouyu.png',
  '赵云':   '/art/portrait-zhaoyun.png',
  '黄盖':   '/art/portrait-huanggai.png',
  '金旋':   '/art/portrait-jinxuan.png',
  '刘度':   '/art/portrait-liudu.png',
  '鲁肃':   '/art/portrait-lusu.png',
  '孙权':   '/art/portrait-sunquan.png',
  '刘备':   '/art/portrait-liubei.png',
  '袁绍':   '/art/portrait-yuanshao.png',
  '曹丕':   '/art/portrait-caopi.png',
  '荀彧':   '/art/portrait-xunyu.png',
  '郭嘉':   '/art/portrait-guojia.png',
  '司马懿': '/art/portrait-simayi.png',
  '陆逊':   '/art/portrait-luxun.png',
  '吕布':   '/art/portrait-lvbu.png',
  '董卓':   '/art/portrait-dongzhuo.png',
  '貂蝉':   '/art/portrait-diaochan.png',
}
